#!/usr/bin/env bash
# refresh-hibp-corpus.sh — Refresh the bundled HIBP top-100k SHA-1 corpus.
#
# Queries the HIBP Pwned Passwords range API for 300 evenly-spaced 5-char
# hex prefixes, collects the top 100,000 entries by prevalence count, and
# writes them to internal/adapter/hibp/data/top.sha1 in place.
#
# Run this periodically (quarterly recommended) or before a production build
# to keep the §5 fallback corpus current with ADR 0070's 100k coverage intent.
#
# Usage:
#   bash scripts/refresh-hibp-corpus.sh
#   bash scripts/refresh-hibp-corpus.sh --want 200000   # fetch more entries
#
# Requirements: python3 (stdlib only), network access to api.pwnedpasswords.com
# Exit codes: 0=success, 1=generation error, 2=size validation failed.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TARGET="$REPO_ROOT/internal/adapter/hibp/data/top.sha1"
WANT="${2:-100000}"

if [[ "${1:-}" == "--want" ]]; then
    WANT="${2:?Usage: $0 --want N}"
fi

echo "==> Fetching HIBP corpus (want $WANT entries) ..."

python3 - "$WANT" > /tmp/hibp_corpus_new.txt 2>/tmp/hibp_corpus_stderr.txt << 'PYEOF'
import sys, time, urllib.request

want = int(sys.argv[1])
prefixes = [f"{i * (0xFFFFF // 300):05X}"[:5] for i in range(300)]
results = {}

def fetch(prefix):
    url = f"https://api.pwnedpasswords.com/range/{prefix}"
    req = urllib.request.Request(url, headers={"User-Agent": "sindireceita-corpus-builder/1.0"})
    with urllib.request.urlopen(req, timeout=15) as r:
        body = r.read().decode()
    for line in body.strip().splitlines():
        suffix, _, count = line.partition(":")
        results[(prefix + suffix).upper()] = int(count)

for i, prefix in enumerate(prefixes):
    for attempt in range(3):
        try:
            fetch(prefix)
            break
        except Exception as e:
            if attempt == 2:
                print(f"SKIP {prefix}: {e}", file=sys.stderr)
            else:
                time.sleep(1)
    if (i + 1) % 50 == 0:
        print(f"  {i+1}/{len(prefixes)} ranges, {len(results)} entries", file=sys.stderr)
    time.sleep(0.05)

top = sorted(results.items(), key=lambda kv: kv[1], reverse=True)[:want]
if len(top) < want:
    print(f"ERROR: only {len(top)} entries collected, need {want}", file=sys.stderr)
    sys.exit(1)
for sha1, _ in top:
    print(sha1)
PYEOF

cat /tmp/hibp_corpus_stderr.txt >&2
ACTUAL=$(wc -l < /tmp/hibp_corpus_new.txt)
echo "==> Collected $ACTUAL entries"

if [[ "$ACTUAL" -lt "$WANT" ]]; then
    echo "ERROR: got $ACTUAL entries, need $WANT" >&2
    exit 2
fi

# Write file with header
{
cat << 'HEADER'
# Bundled top-100k local fallback list (ADR 0070 §5).
#
# Format: one uppercase SHA-1 hex digest of a known-breached password per
# line. Lines starting with '#' or empty lines are ignored. The SHA-1
# format mirrors HIBP's "Pwned Passwords v2" download so the file is a
# drop-in for an offline-mirrored corpus.
#
# Source: HIBP Pwned Passwords range API (https://api.pwnedpasswords.com/range/).
# Generated by querying 300 evenly-spaced 5-char hex prefixes and selecting
# the top entries by prevalence count. Refresh this file periodically
# or at deploy time by running: scripts/refresh-hibp-corpus.sh
#
HEADER
cat /tmp/hibp_corpus_new.txt
} > "$TARGET"

echo "==> Written to $TARGET ($(wc -l < "$TARGET") lines total)"
echo "==> Done. Run 'go test ./internal/adapter/hibp/...' to verify."
